version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - MONGODB_USERNAME=mark
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=star-wars-quotes

volumes:
  mongodb_data:
    driver: local
